<div class="panel panel-default">
  <div class="panel-body">
    <h4>About Accountability Ratings</h4>
    <p>The Texas Education Agency rates more than 8,600 public schools in the state. Districts and campuses are given a rating of either <strong>met standard</strong> or <strong>improvement required</strong> under the accountability system, which has four components, or indices, largely based on the state-mandated STAAR exams: student achievement, student progress, closing performance gaps and post-secondary readiness. In 2015, the state allowed schools to meet either student achievement or student progress to pass, instead of both, as it did in 2014. The state also is not including performance on the math tests in third through eighth grades because the state introduced more rigorous curriculum standards.</p>
    <p>Schools receiving the Met Standard rating may also qualify for distinctions, which are special honors given in a variety of areas.</p>
    <p>For more on the ratings system, TEA offers the <a href="http://ritter.tea.state.tx.us/perfreport/account/2015/manual/index.html" target="_blank">2015 Accountability Manual</a>, or this <a href="http://tea.texas.gov/WorkArea/linkit.aspx?LinkIdentifier=id&ItemID=25769815110&libID=25769815157" target="_blank">one-page summary</a>, and <a href="http://ritter.tea.state.tx.us/perfreport/account/2015/index.html" target="_blank">more.</a></p>
  </div>
</div>
